[user]

"name" = "Linus Arver"
"email" = "linus@ucla.edu"

[lazyjj]
layout = "vertical"

[templates]
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  "\n\n",
  "JJ: --------------------------------------------------------------------\n",
  "JJ: ignore-rest\n",
  surround(
    "#+begin_src txt\n", "#+end_src\n",
    indent("    ", diff.stat(72)),
  ),
  "#+begin_src diff\n",
  diff.git(),
  "#+end_src\n",
)
'''

[colors]

# Diff chunks.
"diff added token" = { fg = "#335533", bg = "#ccffcc", bold = true, underline = false }
"diff removed token" = { fg = "#553333", bg = "#ffcccc", bold = true, underline = false  }

# There are for the line numbers in the left margin, next to the diff chunk lines.
"diff added" = { fg = "#ccffcc", bold = true }
"diff removed" = { fg = "#ffcccc", bold = true }
