# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_hcd" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-id/dm-name-vg0-root";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-id/ata-ST9500420AS_5VJ59T8M-part3";
      fsType = "ext2";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-id/dm-name-vg0-home";
      fsType = "ext4";
    };

  swapDevices = [
    { device = "/dev/disk/by-id/dm-name-vg0-swap"; }
    ];

  nix.maxJobs = 8;
}
