#!/usr/bin/env zsh

color_cycle()
{
	local root_dir
	local direction
	local res

	root_dir="$HOME/syscfg/script/terminal-themes"
	direction=$1

	source <("${root_dir}/change_theme.sh" "${direction}")
}
