#!/usr/bin/env zsh

# dir_info(), a function that acts as an intelligent "ls". This function is
# used by univ_open() to display directory contents, but can be used independently.

dir_info() {
	local file_count
	local mode
	local deref
	local thing

	# NOP if there is nothing to show.
	file_count=$(ls -A1 | wc -l)
	if (( file_count == 0 )); then
		echo "($PWD is empty)"
		return
	fi

	mode="${1:-}"
	shift

	# Add a blank line for legibility.
	echo

	# If we are given a specific thing to list, make sure to dereference any
	# symlinks.
	thing="${1:-}"
	if [[ -n "${thing}" ]]; then
		# Resolve symlinks.
		if [[ -L "${thing}" ]]; then
			echo  "  ${thing} -> $(readlink -f "${thing}")"
			echo "  ---"
			thing="$(readlink -f "${thing}")"
		fi
	fi

	case "${mode}" in
		verbose-by-name)
			ls -Aho --time-style=long-iso --color ${thing} \
				| sed -e 's|^|  |'
			;;
		verbose-by-size)
			ls -AhoSr --time-style=long-iso --color ${thing} \
				| sed -e 's|^|  |'
			;;
		verbose-by-date)
			ls -Ahotr --time-style=long-iso --color ${thing} \
				| sed -e 's|^|  |'
			;;
		brief)
			ls -AC -w $(( COLUMNS - 2 )) --color ${thing} \
				| sed 's|^|  |'
			;;
		*)
            echo >&2 "unrecognized mode \`${mode}'"
            return 1
            ;;
	esac

	# Add a blank line between us and the shell prompt for legibility.
	echo
}
