#!/bin/zsh

dir_info() {
    size=`ls -Ahl | head -n1`
    simple=false
    # show variation of `ls` based on given argument
    case $1 in
        0) # simple
            ls -hs --color | tail -n +2
            simple=true
            ;;
        1) # verbose
            ls -Ahl --color | tail -n +2
            ;;
        2) # simple, but sorted by size
            ls -hsSr --color | tail -n +2
            simple=true
            ;;
        3) # verbose, but sorted by size
            ls -AhlSr --color | tail -n +2
            ;;
        *)
            simple=true
            ls --color
            ;;
    esac

    # show number of files or number of shown vs hidden (as a fraction),
    # depending on which version of `ls` was used
    if $simple; then
        numer=`ls -1 | wc -l`
        denom=`ls -A1 | wc -l`
        if [[ $numer != $denom ]]; then
            echo -n "\n$numer/$denom files; "
        else
            echo -n "\n$denom files; "
        fi
    else
        echo -n "\n`ls -A1 | wc -l` files; "
    fi
    echo -n $size

    # if there is more than 1 file, print name and size of largest file
    if [[ `ls -A1 | wc -l` -gt 1 ]]; then
        big_size=$(ls -hs "$(ls -AS | head -1)" --color | cut -d " " -f1)
        big_name=$(ls -hs "$(ls -AS | head -1)" --color | cut -d " " -f2-)
        echo "; $big_name is $big_size"
    else
        echo
    fi
}
