#!/usr/bin/env zsh

# Usage: `_l_dirs_navigate <next|prev>' to go forward/backwards in directory
# (PWD) history. Use 'dirs -v' to see the directory history stack.

dirs_navigate()
{
	local direction="${1}"
    if [[ "${direction}" == prev ]]; then
		dirs $(dirs -lp | awk 'NR==1{store=$0;next}1;END{print store}') && popd && dir_info brief
    else
		cd -0 && dir_info brief
    fi
}
