#!/usr/bin/env zsh

# Find all files and directories using rg.. Does not traverse git folders by
# default, but this can be "overridden" by simply cd-ing into the .git folder
# first.
f()
{
	if (( $# < 2 )); then
		echo >&2 "usage: $0 <TYPE> [OTHER_RIPGREP_ARGS..] <PATTERN>"
		echo >&2 "args:"
		printf >&2 '%s\n' "$@"
		return 1
	fi

	local subcommand
	local pattern
	local args
	subcommand="${1}"
	shift 1

	# PATTERN is in the last element of "$@". Assign all other elements to
	# $args array.
	args=("$@")
	pattern=${args[-1]}
	unset 'args[-1]'

	# Imply '--' if the pattern starts with a dash. Otherwise the pattern
	# becomes a flag for rg.
	if [[ "${pattern}" =~ ^- ]]; then
		args+=(--)
	fi

	# Determine type of search. Search files and directories for 'f' and text
	# for 't'.
	case "${subcommand}" in
		files|text)
			f_${subcommand} "${pattern}" "${args[@]}"
			;;
		*)
			echo >&2 "$0: unknown search type \`${_type}'"
			return 1
			;;
	esac
}
