#!/usr/bin/env zsh

# Find files with lines that have 80+ columns.
# Usage: find_long_lines TABWIDTH [DIRECTORY] [COLUMNS]

find_long_lines() {
	# Search current directory by default.
	tabwidth="${1}"
	dir="${2:-.}"

	# Search lines longer than 80 columns by default.
	columns="${3:-80}"
	((columns++))

	if (( $# < 1 )) || (( $# > 3 )); then
		echo "usage: $0 TABWIDTH [DIRECTORY] [COLUMNS]"
		return 1
	fi

	if [[ ! -d "$dir" ]]; then
		echo "directory \`$dir' does not exist"
		return 1
	elif [[ -z $tabwidth ]]; then
		echo "second argument must contain a number"
		return 1
	fi

	find "$dir" -type f -not -path "$dir/.git"\
		-exec sh -c "expand -t $tabwidth {} | grep -n \".\{${columns}\}\"" \; -print
}
