#!/usr/bin/env zsh

# Shortcut for "git rebase -i HEAD~<N>" where <N> is a positive integer.
grh()
{
	# The odd-looking "<->" pattern is a zsh-ism tht checks to see that the
	# string only has digits [1].
	# [1]: https://www.zsh.org/mla/users/2007/msg00084.html
	if (( $# != 1 )) || [[ "$1" != <-> ]]; then
		printf "grbh: Need exactly 1 numerical argument.\n"
		return 1
	fi

	# Strip any leading zeroes [1].
	# [1]: https://groups.google.com/d/msg/comp.unix.shell/VI8nIp1plWc/WOhfzd16ug8J
	n="${1#${1%%[!0]*}}"

	if [[ -z $n ]]; then
		printf "grbh: Numerical argument must greater than 0.\n"
		return 1
	fi

	git rebase -i HEAD~"${n}"
}
