#!/usr/bin/env zsh

gst()
{
	! git_contents && return

	local ce="\x1b[0m"

	git -c color.status=always status
	local gstash=$(git stash list)
	if [[ -n "$gstash" ]]; then
		printf "\n\x1b[1;38;5;196m-- STASH --${ce}\n$gstash\n"
	fi
	local groot=$(git rev-parse --show-toplevel)
	local gau=$(git -C "$groot" ls-files -v | grep "^[[:lower:]]")
	if [[ -n "$gau" ]]; then
		printf "\n\x1b[1;38;5;201m-- ASSUME UNCHANGED --${ce}\n$gau\n"
	fi
}
