#!/usr/bin/env zsh

# p() is a shorcut for "ps aux | ag PATTERN".

p()
{
	pattern=$1
	if [[ -z "$pattern" ]]; then
		echo "Need pattern argument"
		return 1
	fi
	type rg 2>&1 >/dev/null
	if (( $? != 0 )); then
		echo "\`rg' is not installed"
		return 1
	fi
	ps aux | rg $pattern
}
