#!/usr/bin/env zsh

# Usage: `p PATTERN' to search for processes named PATTERN.

p()
{
	pattern="${1}"
	if [[ -z "${pattern}" ]]; then
		echo "Need pattern argument"
		return 1
	fi
	type rg 2>&1 >/dev/null
	if (( $? != 0 )); then
		echo "\`rg' is not installed"
		return 1
	fi
	# The process substitution with the `=(...)' syntax prevents the `rg
	# -i ...' process itself from showing up in the results.
	rg -i "${pattern}" =(ps aux)
}
