#!/usr/bin/env zsh

# rand_open() [recurse/norecurse] ['command string'] [extensions...]

# Find all files matching the extension (recursively or not), and store the
# filenames as a list in `/tmp/rand_open_files`. Then, use the given command
# string to open this list of files.

rand_open()
{
	:>/tmp/rand_open_files
	recurse_flag=$1
	command=$2
	if [[ -n $3 ]]; then
		output_ext=".$3"
	else
		output_ext=""
	fi
	output_file=/tmp/rand_open_files${output_ext}
	regex_str=".*\\.\\("
	find_recurse=""
	shift 3

	for ext in $*; do
		regex_str+="$ext\\|"
	done

	regex_str+="\\)$"

	if [[ $recurse_flag == "norecurse" ]]; then
		find_recurse="-maxdepth 1"
	fi

	find -L $PWD ${(z)find_recurse} -type f -iregex $regex_str \
		| shuf --random-source /dev/urandom \
		> $output_file

	if [[ $(wc -l $output_file | cut -d ' ' -f 1) -gt 0 ]]; then
		${(z)command} $output_file
		echo "Chose file \`$chosen'"
	else
		echo "No files to choose."
	fi
}
