#!/bin/zsh

# rand_open() randomly opens a file from the current directory, based on a
# given array ($*) of extensions.

rand_open()
{
	setopt nullglob
	files=()
	recurse_flag=$1
	shift

	for ext in $*; do
		if [[ $recurse_flag == "recurse" ]]; then
			files+=(**/*.$ext)
		else
			files+=(*.$ext)
		fi
	done

	if [[ -n $files ]]; then
		echo ${(F)files} \
			| shuf --random-source /dev/urandom \
			> /tmp/rand_open_files
		univ_open $chosen
		echo "Chose file \`$chosen'"
	else
		echo "No files to choose."
	fi
}
