#!/bin/zsh

# rand_open() [recurse/norecurse] ['command string'] [extensions...]

# Find all files matching the extension (recursively or not), and store the
# filenames as a list in `/tmp/rand_open_files`. Then, use the given command
# string to open this list of files.

rand_open()
{
	:>/tmp/rand_open_files
	recurse_flag=$1
	command=$2
	regex_str=".*\\.\\("
	find_recurse=""
	shift 1

	for ext in $*; do
		regex_str+="$ext\\|"
	done

	regex_str+="\\)$"

	if [[ $recurse_flag == "norecurse" ]]; then
		find_recurse="-maxdepth 1"
	fi

	find $PWD ${(z)find_recurse} -type f -iregex $regex_str \
		| shuf --random-source /dev/urandom \
		> /tmp/rand_open_files

	if [[ $(wc -l /tmp/rand_open_files | cut -d ' ' -f 1) -gt 0 ]]; then
		${(z)command} /tmp/rand_open_files
		echo "Chose file \`$chosen'"
	else
		echo "No files to choose."
	fi
}
