#!/usr/bin/env zsh

# SSH to known machines.

s()
{
	if (( $#@ == 0 )); then
		echo >&2 "Usage: <HOST>"
		return 1
	fi

	local user
	local host="${1}"

	case "${host}" in
	w0) user="ingra" ;;
	*)  user="l" ;;
	esac

	tmux rename-window "${user}@${host}"

	case "${host}" in
	w0)
		ssh -t "${user}@${host}" \"wsl.exe -d NixOS\"
		;;
	*)
		ssh -t "${user}@${host}"
		;;
	esac

	tmux set -w automatic-rename on
}
