#!/usr/bin/env zsh

set_theme() {
	local for_tmux
	local renderer_path
	local root_dir

	root_dir="${HOME}/syscfg/script/terminal-themes"
	renderer_path="${root_dir}/renderControlSequences.dhall"

	# Evaluate control sequences.
	for_tmux="False"
	if [[ -n "${TMUX:-}" ]]; then
		for_tmux="True"
	fi
	source <(dhall text <<< "${renderer_path} ${for_tmux} ${root_dir}/themes/${1}")

	export TERM_COLOR_THEME=$(basename $1)
}
