# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5f3b6d45-4fbc-41bf-b00b-3d7a570029bf";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/c82e45c6-9289-4e0e-b8f1-84a8a4f0acb9";
      fsType = "ext4";
    };

  fileSystems."/mnt/a" =
    { device = "/dev/disk/by-uuid/45a51c5e-ead8-4afb-be41-20f8564898bd";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/eca98203-0adf-4035-be48-ff7cd134d3bf"; }
    ];

  nix.settings.max-jobs = lib.mkDefault 2;
}
