#+TITLE: Literate Emacs configuration
#+AUTHOR: Linus Arver
#+PROPERTY: header-args :tangle no :noweb no-export

* Introduction

We use DOOM emacs (insert link) as a base configuration, and further customize it here in literate form.

** About the top-level PROPERTY settings for this buffer
- These property settings take effect when the buffer is loaded. So that means if you change these settings, you have to reload the buffer for them to take effect.
- We set =:tangle no-export= by default for all source code blocks. This is because the =literate= DOOM module by default tangles all elisp source code blocks to config.el, which defeats the purpose of literate programming (where the raw order of how things are defined do **not** dictate how the end result looks like).
- We set =:noweb no-export= to enable Noweb's =<<LINK>>= syntax in all source code blocks during **tangling** (=config.el= generation) and **evaluation** (when running a code snippet from org-mode with =C-c C-c=). However when we export this org-mode file (e.g., publish it to HTML), we do **NOT** expand it because we want to reveal the underlying noweb structure to the reader. Anyway, turning on noweb for tangling and evaluating allows us to inject source code anywhere and also define them freely.

** Guiding principles

- **Modular output**: We make sure that the output file(s) that are "tangled" out of here stay nice and clean in a modular way. We do **NOT** want to have a giant 2000 line file with everything in it with no modularity, because it hurts readability for the case where we want to debug our configuration at the raw Emacs lisp level.

- **Bird's eye view**: We discuss the most important high-level topics first, and leave the finer details at the end.

* How DOOM loads configs

DOOM requires 3 configuration files in the =$DOOMDIR=:

- =init.el=: This is where DOOM "modules" are loaded; modules are just collections of Emacs packages and configurations. This file is pretty small and straightforward.
- =packages.el=: This is where additional packages are installed (or disabled if they are pulled in by DOOM).
- =config.el=: This is where all of our custom configuration goes. Note that this file can pull in other =*.el= files as well if we want to.

* $DOOMDIR/init.el

#+begin_src elisp :tangle init.el
;;; init.el -*- lexical-binding: t; -*-

;; This file controls what Doom modules are enabled and what order they load
;; in. Remember to run 'doom sync' after modifying it!

;; NOTE Press 'SPC h d h' (or 'C-h d h' for non-vim users) to access Doom's
;;      documentation. There you'll find a "Module Index" link where you'll find
;;      a comprehensive list of Doom's modules and what flags they support.

;; NOTE Move your cursor over a module's name (or its flags) and press 'K' (or
;;      'C-c c k' for non-vim users) to view its documentation. This works on
;;      flags as well (those symbols that start with a plus).
;;
;;      Alternatively, press 'gd' (or 'C-c c d') on a module to browse its
;;      directory (for easy access to its source code).

(doom! :input
       ;;chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row

       :completion
       company           ; the ultimate code completion backend
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ;;ivy               ; a search engine for love and life
       vertico           ; the search engine of the future

       :ui
       deft              ; notational velocity for Emacs
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       ;;doom-quit         ; DOOM quit-message prompts when you quit Emacs
       ;;(emoji +unicode)  ; 🙂
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       hydra
       indent-guides     ; highlighted indent columns
       ;;ligatures         ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       modeline          ; snazzy, Atom-inspired modeline, plus API
       ;;nav-flash         ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints           ; highlight the region an operation acts on
       (popup +all +defaults)   ; tame sudden yet inevitable temporary windows
       ;;tabs              ; a tab bar for Emacs
       ;;treemacs          ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       vc-gutter         ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       window-select     ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       ;;zen               ; distraction-free coding or writing

       :editor
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       (format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       lispy             ; vim for lisp, for people who don't like vim
       multiple-cursors  ; editing in many places at once
       (parinfer +rust)         ; turn lisp into python, sort of
       rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       word-wrap         ; soft wrapping with language-aware indent

       :emacs
       dired             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       ibuffer         ; interactive buffer management
       undo              ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree

       :term
       ;;eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       vterm             ; the best terminal emulation in Emacs

       :checkers
       syntax              ; tasing you for every semicolon you forget
       (spell +flyspell) ; tasing you for misspelling mispelling
       ;;grammar           ; tasing grammar mistake every you make

       :tools
       ;;ansible
       ;;debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       ;;docker
       editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       ;;gist              ; interacting with github gists
       lookup              ; navigate your code and its documentation
       lsp               ; M-x vscode
       magit             ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       ;;pdf               ; pdf enhancements
       ;;prodigy           ; FIXME managing external services & code builders
       rgb               ; creating color strings
       ;;taskrunner        ; taskrunner for all your projects
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       ;;upload            ; map local to remote projects via ssh/ftp

       :os
       (:if IS-MAC macos)  ; improve compatibility with macOS
       tty               ; improve the terminal Emacs experience

       :lang
       ;;agda              ; types of types of types of types...
       ;;beancount         ; mind the GAAP
       ;;cc                ; C > C++ == 1
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       dhall
       (elixir +lsp)           ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp        ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;factor
       ;;faust             ; dsp, but you get to keep your soul
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       (go +lsp)         ; the hipster dialect
       (haskell +lsp)  ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       (json +lsp)            ; At least it ain't XML
       ;;(java +meghanada) ; the poster child for carpal tunnel syndrome
       (javascript +lsp)        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       (latex +lsp)            ; writing papers in Emacs has never been so fun
       ;;lean              ; for folks with too much to prove
       ledger            ; be audit you can be
       ;;lua               ; one-based indices? one-based indices
       markdown          ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       org               ; organize your plain life in plain text
       ;;php               ; perl's insecure younger brother
       ;;plantuml          ; diagrams for confusing people more
       ;;purescript        ; javascript, but functional
       (python +lsp)            ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       (racket +lsp)           ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +lsp)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       (rust +lsp)              ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;(scheme +guile)   ; a fully conniving family of lisps
       (sh +lsp)               ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       (web +lsp)              ; the tubes
       (yaml +lsp)             ; JSON, but readable
       ;;zig               ; C, but simpler

       :email
       ;;(mu4e +org +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)

       :app
       ;;calendar
       ;;emms
       everywhere        ; *leave* Emacs!? You must be joking
       ;;irc               ; how neckbeards socialize
       ;;(rss +org)        ; emacs as an RSS reader
       ;;twitter           ; twitter client https://twitter.com/vnought

       :config
       literate
       (default +bindings +smartparens))

<<config-file-location>>
<<leader-key>>
#+end_src

** Change the literate DOOM config file location
#+begin_src elisp
(setq +literate-config-file (concat doom-private-dir "README.org"))
#+end_src

** Change DOOM's leader key from "SPC" to ","

Here's a rundown of these all-important leader keys:

- =doom-leader-key=: Global leader key for global functions that should work regardless of whatever major mode is active.
- =doom-leader-alt-key=: Same as =doom-leader-key=, but accessible from Evil's Insert and Emacs states.
- =doom-localleader-key=: Major-mode-specific leader key. Brings up lots of commands that are specific to the current major mode.
- =doom-localleader-alt-key=: Same as =doom-localleader-alt-key=, but accessible from Evil's Insert and Emacs states.

NOTE: For all of DOOM's bindings, you can just press the keys and pause, and the minibuffer will tell you what keys are available. So you can explore what options are available interactively!

We use F7 for the alternate leader key in insert mode, because C-, is not a thing (or, at least it doesn't work in terminal Emacs).

FIXME: Use C-, instead (the only reason we don't see it in the terminal is because of Alacritty trying to emulate old terminal behavior)

#+name: leader-key
#+begin_src elisp
(setq doom-leader-key ","
      doom-leader-alt-key "<f7>"
      doom-localleader-key ", m"
      doom-localleader-alt-key "<f7> m")
#+end_src

* $DOOMDIR/packages.el

#+begin_src elisp :tangle packages.el
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

;; To install a package with Doom you must declare them here and run 'doom sync'
;; on the command line, then restart Emacs for the changes to take effect -- or
;; use 'M-x doom/reload'.

;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;(package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/raxod502/straight.el#the-recipe-format
;(package! another-package
;  :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;(package! this-package
;  :recipe (:host github :repo "username/repo"
;           :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;(package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;(package! builtin-package :recipe (:nonrecursive t))
;(package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see raxod502/straight.el#279)
;(package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;(package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;(unpin! pinned-package)
;; ...or multiple packages
;(unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;(unpin! t)
(package! kakapo-mode)
<<package-zenburn-theme>>
#+end_src

* $DOOMDIR/config.el

This is the final structured output of =$DOOMDIR/config.el=, which is a special file that DOOM recognizes. Because of the way it acts as the "main" configuration file, you can think of it as =init.el= in the traditional Emacs sense. DOOM has its own =init.el= but that is another matter.

Note that this file is pretty much **required** and acts as the base for all other configurations that are pulled in. And so we define it first here.

#+begin_src elisp :tangle config.el
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

<<doom-bug-workarounds>>

<<name-and-email>>

<<theme>>

<<org>>

<<line-numbers>>

<<easy-esc>>

<<remap-s>>
<<remap-leader-h>>
<<remap-leader-n>>

<<navigation-buffer-intra>>
<<navigation-buffer-inter>>

<<window-management>>

<<tab-management>>


;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+end_src

#+RESULTS:
: tab-new

* DOOM bug workarounds

Here are some workarounds for upstream bugs that have not yet been fixed.

#+name: doom-bug-workarounds
#+begin_src elisp
<<iedit-embark-conflict>>
#+end_src

** https://github.com/hlissner/doom-emacs/issues/5374 (Key-binding conflict between iedit and embark)
#+name: iedit-embark-conflict
#+begin_src elisp
(use-package! iedit
  :when (featurep! :completion vertico)
  :defer t
  :init
  ;; Fix conflict with embark.
  (setq iedit-toggle-key-default nil))
#+end_src

* Global key-bindings
** Enter Evil normal state quickly (default: "ESC" key)

Make "kj" behave as ESC key.
#+name: easy-esc
#+begin_src elisp
(use-package! evil-escape
  :config
  (setq evil-escape-key-sequence "kj"))
#+end_src

#+RESULTS: easy-esc
: evil-substitute

** Override default DOOM bindings

*** Basic buffer navigation

**** Intra-buffer navigation

We remap Backspace and Space keys because they are by default aliases to =h= and =l= keys, respectively, making them redundant.

#+name: navigation-buffer-intra
#+begin_src elisp
(map! :m "SPC" (cmd!! #'l/scroll-jump 10)
      :mn "DEL" (cmd!! #'l/scroll-jump -10))
(defun l/scroll-jump (cnt)
  "Scroll by CNT lines."
  (interactive "p")
  (forward-line cnt)
  (evil-scroll-line-to-center nil))
#+end_src

**** Intra-buffer navigation

We remap H and L keys because they do almost-useless things (go to the top and bottom of the current window).

#+name: navigation-buffer-inter
#+begin_src elisp
(map! :m "H" #'previous-buffer
      :m "L" #'next-buffer)
#+end_src

*** Restore old "s" key behavior in Evil normal mode

Remap =s= back to =evil-substitute=, instead of =evil-snipe-s=. However, map =S= to evil-snipe-s because it can't hurt and we never use =S= in vanilla Vim anyway.
#+name: remap-s
#+begin_src elisp
(remove-hook 'doom-first-input-hook #'evil-snipe-mode)
(map! :n "S" #'evil-snipe-s)
#+end_src

*** Remap the "+help" function from ", h" to ", H"

#+name: remap-leader-h
#+begin_src elisp
(map! :leader :desc "help" "H" help-map)
#+end_src

*** Remap the "+notes" function from ", n" to ", N"

FIXME: This can't be done because "n" is bound to a map prefix which is not a function that can be called.

#+name: remap-leader-n
#+begin_src elisp
;(map! :leader :desc "notes" "N" help-map)
#+end_src

** Window management

#+name: window-management
#+begin_src elisp
<<window-splits>>
<<window-deletion>>
<<window-navigation>>
#+end_src

*** Splits (window creation)

Splitting windows happens so frequently that we put these bindings at the top level just after the leader key.

#+name: window-splits
#+begin_src elisp
(map! :leader "h" #'l/split-vertically
      :leader "v" #'l/split-horizontally)
(defun l/split-vertically ()
  "Split window verically."
  (interactive)
  (split-window-vertically)
  (balance-windows))
(defun l/split-horizontally ()
  "Split window horizontally."
  (interactive)
  (split-window-horizontally)
  (balance-windows))
#+end_src

*** Deletion

If there are multiple windows, close the current window. Otherwise close the current tab if there are mulitple tabs. Otherwise, try to exit emacs.

We take care to tread around so-called "auxiliary" buffers, which are auto-generated buffers from various emacs modes/packages.

FIXME: remap doom emacs' "q" binding to something else

#+name: window-deletion
#+begin_src elisp
(map! :leader "q" #'l/quit-buffer)
(defun l/quit-buffer ()
  "Tries to escape the current buffer by closing it (or moving to a
non-auxiliary buffer if possible). Calls `l/gc-views' to handle any sort of
window management issues."
  (interactive)
  (let*
    (
      (original-bufname (buffer-name))
      (aux-buffer-rgx "^ *\*.+\*$")
      (is-aux-buffer (l/buffer-looks-like original-bufname '("^ *\*.+\*$")))
      (buffers (mapcar 'buffer-name (buffer-list)))
      (primary-buffers-count
        (length
          (seq-filter
            '(lambda (bufname) (not (string-match "^ *\*.+\*$" bufname)))
            buffers)))
      (primary-buffer-exists (> primary-buffers-count 0))
    )

    ; If we're on a magit-controlled buffer, do what magit expects and simulate
    ; pressing C-c C-c (with-editor-finish).
    (catch 'my-catch
      (progn
        (if (bound-and-true-p with-editor-mode)
          (if (buffer-modified-p)
            ; If there are any unsaved changes, either discard those changes or do
            ; nothing.
            (if (y-or-n-p "l/quit-buffer: Invoke (with-editor-cancel) to cancel the editing of this buffer?")
              (with-editor-cancel t)
              ; Use catch/throw to stop execution.
              (throw 'my-catch (message "l/quit-buffer: Aborting (doing nothing).")))
            (with-editor-finish t)))
        ; Close the current view (or exit the editor entirely), but only if we
        ; originally tried to close a non-"auxiliary" buffer. An "auxiliary"
        ; buffer is any buffer that is created in support of another major
        ; buffer. For example, if we open buffer "A", but then run `M-x
        ; describe-function' so that we're on a "*Help*" buffer, do NOT close
        ; the view (and exit emacs). In other words, such "auxiliary" buffers,
        ; when we want to quit from them, we merely want to just switch over to
        ; a primary (non-auxiliary) buffer.
        ;
        ; If we *only* have auxiliary buffers, then of course just quit.
        (if (and is-aux-buffer primary-buffer-exists)
          ; Cycle through previous buffers until we hit a primary
          ; (non-auxiliary) buffer.
          (progn
            (catch 'buffer-cycle-detected
              (while
                (string-match "^ *\*.+\*$" (buffer-name))
                ; Break loop if somehow our aux-buffer-rgx failed to account for all
                ; hidden/aux buffers and we are just looping over and over among the
                ; same list of actual auxiliary buffers.
                (if (string= original-bufname (buffer-name))
                  (throw 'buffer-cycle-detected
                    (message "l/quit-buffer: Buffer cycle detected among auxiliary buffers; invoking `l/gc-views'."))
                  (previous-buffer))))
              ; If we've broken the loop (due to a cycle), run (l/gc-views) as
              ; it is better than doing nothing.
              (l/gc-views))
          (l/gc-views))))))

; Either close the current window, or if only one windw, use the ":q" Evil
; command; this simulates the ":q" behavior of Vim when used with tabs to
; garbage-collect the current "view".
(defun l/gc-views ()
  "Vimlike ':q' behavior: close current window if there are split windows;
otherwise, close current tab."
  (interactive)
  (let
    ( (one-tab (= 1 (length (tab-bar-tabs))))
      (one-window (one-window-p)))
    (cond
      ; If current tab has split windows in it, close the current live
      ; window.
      ((not one-window) (delete-window) (balance-windows) nil)
      ; If there are multiple tabs, close the current one.
      ((not one-tab) (tab-bar-close-tab) nil)
      ; If there is only one tab, just try to quit (calling tab-bar-close-tab
      ; will not work, because if fails if there is only one tab).
      (one-tab
        (progn
          ; When closing the last frame of a graphic client, close everything we
          ; can. This is to catch graphical emacsclients that do not clean up
          ; after themselves.
          (if (display-graphic-p)
            (progn
              ; Minibuffers can create their own frames --- but they can linger
              ; around as an invisible frame even after they are deleted. Delete all
              ; other frames whenever we exit from a single visible daemon frame,
              ; because there is no point in keeping them around. If anything they
              ; can hinder detection of "is there a visible frame?" logic from the
              ; shell.
              (delete-other-frames)
              ; While we're at it, also close all buffers, because it's annoying to
              ; have things like Helm minibuffers and the like sitting around.
              (mapc
                'kill-buffer
                (seq-filter
                  (lambda (bufname)
                    (not (l/buffer-looks-like bufname
                      '(
                      ; Do not delete buffers that may be open which are for git
                      ; rebasing and committing. This is in case these buffers
                      ; are open in other clients which may still be working on
                      ; these buffers.
                      "^COMMIT_EDITMSG"
                      "^git-rebase-todo"
                      ; This catches buffers like 'addp-hunk-edit.diff' which is
                      ; used during surgical edits of what to stage ('e' option
                      ; to the 'git add -p' command).
                      ".*hunk-edit.diff"
                      ; Don't delete system buffers buffers.
                      "^\*Messages\*"))))
                  (mapcar 'buffer-name (buffer-list))))))
          (evil-quit)) nil))))

(defun l/buffer-looks-like (bufname regexes)
  "Return t if the buffer name looks like any of the given regexes."
  (interactive)
  (eval (cons 'or (mapcar
    (lambda (rgx) (string-match rgx bufname)) regexes))))
#+end_src

*** Navigation

Make TAB/S-TAB cycle through windows. We have to take care to disable the TAB keybinding that comes with =evil-org=.

The default binding in evil-org-mode-map is to =org-cycle=, but we don't really use it much because our org files tend to be on the smaller side (well, even if they're big, we just use window splits and tabs aggressively so navigating is never a real issue).

FIXME: Unfortunately this breaks the RET keybinding in org-mode source blocks (in insert mode), as described here: https://www.reddit.com/r/DoomEmacs/comments/pgaf92/ret_key_in_orgmode_source_code_block_in_insert/hba67l4?utm_source=share&utm_medium=web2x&context=3

#+name: window-navigation
#+begin_src elisp
;(after! evil-org
;  (map! (:map evil-org-mode-map
;           :mnv "TAB" #'other-window
;           :mnv "<backtab>" (cmd!! #'other-window -1))
;        :mnv "TAB" #'other-window
;        :mnv "<backtab>" (cmd!! #'other-window -1)))
#+end_src

#+RESULTS: window-navigation

** Tabs

#+name: tab-management
#+begin_src elisp
<<tab-ui>>
<<tab-navigation>>
<<tab-creation>>
#+end_src

*** UI
#+name: tab-ui
#+begin_src elisp
(setq tab-bar-show t
      tab-bar-new-button-show nil
      tab-bar-close-button-show nil
      tab-bar-separator "  ")
#+end_src

*** Creation

We don't have any code for deleting a tab because we only delete windows instead (and only delete the tab when the tab has only one window in it). This is so that we don't accidentally close a tab with a bunch of window splits, which can be laborious to reconstruct.

FIXME: try to see if we can remap this to just "n" instead of "N".

#+name: tab-creation
#+begin_src elisp
(map! :leader "N" #'tab-new)
#+end_src

*** Navigation
#+name: tab-navigation
#+begin_src elisp
(map! :mi "C-l" #'tab-next
      :mi "C-h" #'tab-previous)
(map! :leader "h" #'l/split-vertically
      :leader "v" #'l/split-horizontally)
#+end_src

* Colors

First install the zenburn-theme package, then load it by setting =doom-theme= to it.

#+name: package-zenburn-theme
#+begin_src elisp
(package! zenburn-theme)
#+end_src

#+name: theme
#+begin_src elisp
(setq doom-theme 'zenburn)
#+end_src

* Org mode
#+name: org
#+begin_src elisp
;(after! (evil-org kakapo-mode)
;  (map! (:map (org-mode-map evil-org-mode-map)
;           :i [return] #'kakapo-ret-and-indent
;           :i "RET" #'kakapo-ret-and-indent)))

<<org-misc>>
#+end_src

** Misc

If you use "org" and don't want your org files in the default location below, change org-directory. It must be set before org loads!
#+name: org-misc
#+begin_src elisp
(setq org-directory "~/lo/note/")
#+end_src

* Misc settings

** Personal information

Some functionality uses this to identify you, e.g. GPG configuration, email clients, file templates and snippets.
#+name: name-and-email
#+begin_src elisp
(setq user-full-name "Linus Arver"
      user-mail-address "linusarver@gmail.com")
#+end_src

This determines the style of line numbers in effect. If set to "nil", line numbers are disabled. For relative line numbers, set this to "relative".
#+name: line-numbers
#+begin_src elisp
(setq display-line-numbers-type nil)
#+end_src

FIXME: we have to manually turn on kakapo-mode in this org buffer. How can we turn it on automatically?

#+name: kakapo
#+begin_src elisp
(package! kakapo-mode
  :config
  (add-hook 'text-mode-hook #'kakapo-mode)
  (add-hook 'org-mode-hook #'kakapo-mode)
  (add-hook 'prog-mode-hook #'kakapo-mode))

(after! kakapo-mode
  (kakapo-mode))
#+end_src

* Reference

#  LocalWords:  iedit ESC kj LocalWords DOOM's SPC Evil's minibuffer
