#!/usr/bin/env zsh

# change X's cursor (mouse pointer) from the default "X" to an arrow pointer
xsetroot -cursor_name left_ptr &

# use the 'unclutter' program to disable showing the mouse pointer after X seconds
# however, disable 'unclutter' for mouse-intensive programs like Blender and Gimp
# '-noevents' flag is for xmonad compatibility
unclutter -grab -noevents -idle 10 -not Blender Gimp &

# initialize keyboard in a sane manner
~/syscfg/script/sys/initkeys.sh

# set input method to uim
export GTK_IM_MODULE=uim
export QT_IM_MODULE=uim
export XMODIFIERS=@im=uim
uim-xim &

# start the emacs daemon
emacs --daemon &

case $(hostname) in
    exelion)
        # start Music Player Demon (mpd) with customized config file (instead of making an ugly symlink at the default-looked-at /etc/mpd.conf
        mpd ~/syscfg/mpd/cfg-alsa
        # start second MPD for remote listening via icecast
        # NOTE: this is necessary even though MPD can output to multiple audio streams at the same time, since we DON'T want this remote listener, with his mpd client, change what comes out of the physical speakers located at the server
        mpd ~/syscfg/mpd/cfg-icecast

        # start icecast to stream mpd music over the LAN
        # NOTE: the -b flag daemonizes it (necessary here for purposes of xinit going through every command; see "man init" for details about xinitrc and init's behavior)
        # the -c flag points to the configuration file
        icecast -b -c ~/syscfg/icecast/cfg.xml

        # turn on numlock for keypad by default
        # numlockx &

        # start xscreensaver
        #xscreensaver -no-splash &
    ;;
    luxion)
    ;;
    *)
    ;;
esac

# start a random screensaver
# dependencies: shantz-xwinwrap-bzr from AUR; xscreensaver
#==========================================================================================================================#
# case $(($RANDOM%4)) in                                                                                                   #
#     0)                                                                                                                   #
#         xwinwrap -ov -fs -ni -- /usr/lib/xscreensaver/cubicgrid -root -window-id WID -delay 10000 -speed 0.5 -ticks 35 & #
#     ;;                                                                                                                   #
#     1)                                                                                                                   #
#         xwinwrap -ov -fs -ni -- /usr/lib/xscreensaver/intermomentary -root -window-id WID &                              #
#     ;;                                                                                                                   #
#     2)                                                                                                                   #
#         xwinwrap -ov -fs -ni -- /usr/lib/xscreensaver/cwaves -root -window-id WID -colors 16000 &                        #
#     ;;                                                                                                                   #
#     3)                                                                                                                   #
#         xwinwrap -ov -fs -ni -- /usr/lib/xscreensaver/surfaces -root -window-id WID -points -spin -delay 38000 &         #
#     ;;                                                                                                                   #
# esac                                                                                                                     #
#==========================================================================================================================#

exec xmonad
