#!/usr/bin/env zsh

# change X's cursor (mouse pointer) from the default "X" to an arrow pointer
xsetroot -cursor_name left_ptr &

# use the 'unclutter' program to disable showing the mouse pointer after X seconds
# however, disable 'unclutter' for mouse-intensive programs like Blender and Gimp
# '-noevents' flag is for xmonad compatibility
unclutter -grab -noevents -idle 10 -not Blender Gimp &

# initialize keyboard in a sane manner
~/syscfg/script/sys/initkeys.sh

# set input method to uim
export GTK_IM_MODULE=uim
export QT_IM_MODULE=uim
export XMODIFIERS=@im=uim
uim-xim &

# start the emacs daemon
emacs --daemon &

case $(hostname) in
    k0)
        icecast -b -c ~/syscfg/icecast/cfg.xml

        # turn on numlock for keypad by default
        # numlockx &
    ;;
    k1)
        amixer -q set Speaker mute
    ;;
    k2)
        amixer -q set "External Amplifier" mute
    ;;
    *)
    ;;
esac

exec xmonad
