#!/bin/bash

# change X's cursor (mouse pointer) from the default "X" to an arrow pointer
xsetroot -cursor_name left_ptr

# use the 'unclutter' program to disable showing the mouse pointer after X seconds
# however, disable 'unclutter' for mouse-intensive programs like Blender and Gimp
# '-noevents' flag is for xmonad compatibility
unclutter -grab -noevents -idle 10 -not Blender Gimp &

# run the xmonad-utils program 'hhp', which is the haskell version of 'unclutter'
# by default the mouse is hidden after 10 seconds of inactivity
#hhp &

# DISABLE CAPSLOCK KEY, and instead use it as the MODKEY in xmonad!!
xmodmap -e "remove Lock = Caps_Lock"
#xmodmap -e "clear mod3" <--- unnecessary b/c 'xmodmap' returns BLANK for mod3 on default settings
xmodmap -e "add mod3 = Caps_Lock"

# set default repeat rate (miliseconds delay, keystroke speed)
xset r rate 300 80

# start xscreensaver
xscreensaver -no-splash &

case $(hostname) in
    exelion)
        # start Music Player Demon (mpd) with customized config file (instead of making an ugly symlink at the default-looked-at /etc/mpd.conf
        mpd /home/listdata/syscfg/mpd/cfg-alsa
        # start second MPD for remote listening via icecast
        # NOTE: this is necessary even though MPD can output to multiple audio streams at the same time, since we DON'T want this remote listener, with his mpd client, change what comes out of the physical speakers located at the server
        mpd /home/listdata/syscfg/mpd/cfg-icecast

        # start icecast to stream mpd music over the LAN
        # NOTE: the -b flag daemonizes it (necessary here for purposes of xinit going through every command; see "man init" for details about xinitrc and init's behavior)
        # the -c flag points to the configuration file
        icecast -b -c /home/listdata/syscfg/icecast/cfg.xml

        # turn on numlock for keypad by default
        numlockx &
    ;;
    luxion)
    ;;
    *)
    ;;
esac

# start SCIM
export XMODIFIERS=@im=SCIM
export GTK_IM_MODULE="scim"
export QT_IM_MODULE="scim"
scim -d


# start a random screensaver
# dependencies: shantz-xwinwrap-bzr from AUR; xscreensaver
#==========================================================================================================================#
# case $(($RANDOM%4)) in                                                                                                   #
#     0)                                                                                                                   #
#         xwinwrap -ov -fs -ni -- /usr/lib/xscreensaver/cubicgrid -root -window-id WID -delay 10000 -speed 0.5 -ticks 35 & #
#     ;;                                                                                                                   #
#     1)                                                                                                                   #
#         xwinwrap -ov -fs -ni -- /usr/lib/xscreensaver/intermomentary -root -window-id WID &                              #
#     ;;                                                                                                                   #
#     2)                                                                                                                   #
#         xwinwrap -ov -fs -ni -- /usr/lib/xscreensaver/cwaves -root -window-id WID -colors 16000 &                        #
#     ;;                                                                                                                   #
#     3)                                                                                                                   #
#         xwinwrap -ov -fs -ni -- /usr/lib/xscreensaver/surfaces -root -window-id WID -points -spin -delay 38000 &         #
#     ;;                                                                                                                   #
# esac                                                                                                                     #
#==========================================================================================================================#

exec xmonad
