#!/bin/zsh

# set various terminal launcher paths
term1=~/syscfg/shellscripts/sys/terms/wb.sh
term2=~/syscfg/shellscripts/sys/terms/bw.sh
term3=~/syscfg/shellscripts/sys/terms/wB.sh

# check for hostname
case $(hostname) in
    exelion)
        $term2 -e ncmpcpp &
        $term1 -e alsamixer &
        $term2 -n iftop -e sudo iftop -B -i eth1 &
        $term1 -e htop &
        $term3 -e rtorrent &
        $term1 -name WeeChat -e weechat-curses &

        # the -passfile option ONLY WORKS if alpine is compiled with
        # "--with-passfile=some-default-file-without-directory-structure", and alpine will then
        # by default ask if you want to save passwords to disk, and use the file specified in
        # the --with-passfile option at compile/configure time; setting this option gives alpine
        # the ability to use a DIFFERENT location for a password file at each time it is run, with
        # the "-passfile" option
        $term1 -e alpine -p ~/.alpine/cfg -passfile ~/.alpine-pass &
        firefox
    ;;
    luxion)
        $term1 -e alsamixer &
        $term2 -n iftop -e sudo iftop -B -i eth0 &
        $term1 -e htop &
        $term1
    ;;
    aether)
        $term1 -e alsamixer &
        $term2 -n iftop -e sudo iftop -B -i eth0 &
        $term1 -e htop &
        $term3 -e rtorrent &
        $term1
    ;;
    *)
    ;;
esac

# vim:syntax=zsh
