#!/bin/bash

# for some reason, not all the default settings like font and scrollbar are NOT loaded when this
# script is executed from Xmonad's hotkey system, so, I need to add these settings manually
# into the command line (notice that, this gives me the added advantage of giving certain
# programs DIFFERENT colors, fonts, and so on)!

# check for HOSTNAME
HOSTNAME=$(hostname)
case "${HOSTNAME}" in
    exelion)
        urxvt -e ncmpcpp
        urxvt -e alsamixer
        urxvt -n iftop -e sudo iftop -B -i eth1
        urxvt -e htop

        # WEECHAT
        urxvt -name WeeChat -e weechat-curses

        # the -passfile option ONLY WORKS if alpine is compiled with
        # "--with-passfile=some-default-file-without-directory-structure", and alpine will then
        # by default ask if you want to save passwords to disk, and use the file specified in
        # the --with-passfile option at compile/configure time; setting this option gives alpine
        # the ability to use a DIFFERENT location for a password file at each time it is run, with
        # the "-passfile" option
        urxvt -e alpine -p ~/.alpine/cfg -passfile ~/.alpine-pass
        #urxvt -e rtorrent
        firefox
        #blender
    ;;
    luxion)
        urxvt -e alsamixer
        urxvt -n iftop -e sudo iftop -B -i eth0
        urxvt -e htop
        urxvt
    ;;
    aether)
        urxvt -e alsamixer
        urxvt -n iftop -e sudo iftop -B -i eth0
        urxvt -e htop
        urxvt -e rtorrent
        urxvt
    ;;
    *)
    ;;
esac
