#!/bin/zsh

# set various terminal launcher paths
term1=~/syscfg/script/sys/terms/wb.sh
term2=~/syscfg/script/sys/terms/bw.sh
term3=~/syscfg/script/sys/terms/wB.sh

# check for hostname
case $(hostname) in
    exelion)
        firefox &
        $term2 -e ncmpcpp &
        $term1 -e alsamixer &
        $term2 -n iftop -e sudo iftop -B -i eth1 &
        $term1 -e htop &
        $term3 -e rtorrent &
        $term1 -name WeeChat -e weechat-curses &
        $term1
    ;;
    luxion)
        $term1 -e alsamixer &
        $term2 -n iftop -e sudo iftop -B -i eth0 &
        $term1 -e htop &
        $term1
    ;;
    aether)
        firefox &
        $term1 -e alsamixer &
        $term2 -n iftop -e sudo iftop -B -i eth0 &
        $term1 -e htop &
        $term3 -e rtorrent &
        $term1
    ;;
    *)
    ;;
esac

# vim:syntax=zsh
