#!/usr/bin/env bash

# See
# https://superuser.com/questions/1006505/where-to-put-x11-xquartz-configuration-on-os-x.

getvalue() {
    value=$(xset q |\
        fgrep "$2" |\
        sed -e 's/^.*'"$2"':[[:space:]]*//' -e 's/[[:space:]].*//')
    [[ -z "$value" ]] && value="not set"
    eval $1=$value
}

WANT_DELAY=250
WANT_RATE=80

# Continuously call xset whenever we detect a deviation from our desired
# delay/rate.
while :; do
    X11_PID=$(pgrep Xquartz)
    if [[ -n "$X11_PID" ]]; then
        getvalue XSET_RATE "repeat rate"
        getvalue XSET_DELAY "repeat delay"
        if [[ "x$XSET_RATE"  != "x$WANT_RATE" ]]\
            || [[ "x$XSET_DELAY" != "x$WANT_DELAY" ]]; then
            xset r rate $WANT_DELAY $WANT_RATE
        fi
    fi
    sleep 1
done
