[package]
name = "lh_lightning"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "lh_lightning"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
git2 = "0.14"
rustler = "0.22.2"
lh_common = { path = "../../../lh_common"}
