#!/usr/bin/env bash

# Sync notmuch to offlineimap.
notmuch new

# Organize messages with tags.
notmuch tag --batch --input="$HOME"/tmp/notmuch-tags

# Move deleted messages to "trash" folder.
notmuch search --output=files \
	tag:deleted \
	'(not (folder:trash or folder:spam or tag:sent))' \
	| while read -r f; do

	mv "$f" ~/mail/trash/cur

done
