#!/usr/bin/env bash

# Sync notmuch to offlineimap.
notmuch new

# Organize messages with tags.
notmuch tag --batch --input="$HOME"/tmp/notmuch-tags

# Move deleted files to Trash folder.
for f in $(notmuch search --output=files \
	tag:deleted \
	'(not (folder:Trash or folder:Spam or tag:sent))'); do

	mv "$f" ~/mail/Trash/cur
done
