#!/usr/bin/env bash

# Detect trailing whitespace, trailing blank lines at EOF, and files without
# final newlines in the staging area.

error_found=0
noeol="^\\\ No newline at end of file"

# Detect trailing whitespace.
if (($(git diff --check --cached | wc -l))); then
	echo "You are attempting to add trailing whitespace and/or blank lines!"
	echo "Please fix the following:"
	echo
	git diff --check --cached
	error_found=1
fi

# Detect files without a newline at the end.
if (($(git diff --cached | grep "$noeol" | wc -l))); then
	declare -a files
	for file in $(git diff --cached --name-only); do
		# Condition 1: check if file with noeol message has not been deleted
		# (i.e., cached diffs of such files are OK if we are deleting those same
		# files).
		#
		# Condition 2: check that the noeol message appears at the very end of
		# the diff --- it could be that we are fixing such files by adding a
		# newline (in which case the noeol message will still appear, but
		# followed by some content.)
		if (($(git status --porcelain "$file" | grep -v "^D" | wc -l))) \
			&& (($(git diff --cached "$file" \
				| tail -n1 | grep "$noeol" | wc -l))); then
			files+=("$file")
		fi
	done
	if ((${#files[@]})); then
		echo "You are attempting to add text without a final newline!"
		echo "Please fix the following:"
		for file in ${files[*]}; do
			echo "  $file"
		done
		error_found=1
	fi
fi

if [ $error_found == "1" ]; then
	exit 1
fi
